/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Influencer {
  'id' : string,
  'alignmentScore' : bigint,
  'avgEngagement' : number,
  'exampleTweetUrls' : Array<string>,
  'niche' : string,
  'savedAt' : bigint,
  'handle' : string,
  'followers' : bigint,
}
export interface SearchQuery {
  'id' : string,
  'createdAt' : bigint,
  'niches' : Array<string>,
  'minEngagement' : number,
  'minFollowers' : bigint,
  'projectDescriptions' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSavedInfluencers' : ActorMethod<[], Array<Influencer>>,
  'getSearchHistory' : ActorMethod<[], Array<SearchQuery>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeInfluencer' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveInfluencer' : ActorMethod<[Influencer], undefined>,
  'saveSearchQuery' : ActorMethod<[SearchQuery], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];