/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Influencer = IDL.Record({
  'id' : IDL.Text,
  'alignmentScore' : IDL.Nat,
  'avgEngagement' : IDL.Float64,
  'exampleTweetUrls' : IDL.Vec(IDL.Text),
  'niche' : IDL.Text,
  'savedAt' : IDL.Int,
  'handle' : IDL.Text,
  'followers' : IDL.Nat,
});
export const SearchQuery = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'niches' : IDL.Vec(IDL.Text),
  'minEngagement' : IDL.Float64,
  'minFollowers' : IDL.Nat,
  'projectDescriptions' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchXApiRaw' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSavedInfluencers' : IDL.Func([], [IDL.Vec(Influencer)], ['query']),
  'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchQuery)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getXApiTokenStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeInfluencer' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveInfluencer' : IDL.Func([Influencer], [], []),
  'saveSearchQuery' : IDL.Func([SearchQuery], [], []),
  'setXApiToken' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Influencer = IDL.Record({
    'id' : IDL.Text,
    'alignmentScore' : IDL.Nat,
    'avgEngagement' : IDL.Float64,
    'exampleTweetUrls' : IDL.Vec(IDL.Text),
    'niche' : IDL.Text,
    'savedAt' : IDL.Int,
    'handle' : IDL.Text,
    'followers' : IDL.Nat,
  });
  const SearchQuery = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'niches' : IDL.Vec(IDL.Text),
    'minEngagement' : IDL.Float64,
    'minFollowers' : IDL.Nat,
    'projectDescriptions' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchXApiRaw' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSavedInfluencers' : IDL.Func([], [IDL.Vec(Influencer)], ['query']),
    'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchQuery)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getXApiTokenStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeInfluencer' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveInfluencer' : IDL.Func([Influencer], [], []),
    'saveSearchQuery' : IDL.Func([SearchQuery], [], []),
    'setXApiToken' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };